adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.0
checkpointing_steps: 5000
dataset_path: /scratch/ssing631/animals
device: cuda:0
gradient_accumulation_steps: 1
hidden_dim: 2048
img_size: 1024
log_image_frequency: 500
log_validation: 5000
lr: 1.0e-05
max_crops: 7
max_grad_norm: 1.0
max_train_steps: 500000
mixed_precision: fp16
n_val_images: 10
num_attention_heads: 32
num_layers: 4
num_workers: 8
output_dir: training_results/train_animals
report_to: wandb
resume_from_path: null
resume_from_step: null
seed: null
sketch_prob: 0.0
train_batch_size: 64
use_ref: false
val_dataset_path: /scratch/ssing631/animals
